name: my_delivery_app
description: A cutting-edge delivery app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  dio: ^5.1.2
  cached_network_image: ^3.2.3
  easy_localization: ^3.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  firebase_analytics: ^10.4.2
  rive: ^0.11.1
  google_fonts: ^4.0.4
  change_app_package_name: ^1.2.0
  google_sign_in: ^6.2.1
  flutter_svg: ^1.0.0
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  flutter_blurhash: ^0.8.2
  share_plus: ^9.0.0
  flutter_markdown: ^0.7.2+1
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1
  flutter_staggered_animations: ^1.1.1
  fl_chart: ^0.68.0
  cloud_functions: 4.7.6
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.1.0
  file_picker: ^5.2.10
  flutter_colorpicker: ^1.1.0
  flutter_html: 3.0.0-beta.2
  pdf: ^3.10.4
  webview_flutter: ^4.0.0
  flutter_slidable: ^0.6.0
  url_launcher: ^6.1.10
  provider: ^6.1.2
  flutter_stripe: ^9.0.0+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  lottie: ^2.3.2
  http: ^1.2.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  html: ^0.15.0
  flutter_staggered_grid_view: ^0.6.2
  shimmer: ^2.0.0  




  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/fast-food.png
    - assets/images/carrefour.png
    - assets/images/medicine.png
    - assets/images/restaurant.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 