import '../models/product.dart';

class MedicineService {
  Future<List<Product>> getMedicineProducts() async {
    await Future.delayed(Duration(seconds: 2));

    return [
      Product(
        id: '1',
        name: 'Doliprane',
        price: 15.99,
        imageUrl: 'https://tse3.mm.bing.net/th?id=OIP.5omy_4pWxIQz1YEbBA915wHaHa&pid=Api&P=0&h=180',
        description: 'Analgésique et antipyrétique à base de paracétamol',
        category: 'Analgésiques et Antipyrétiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 95,
        averageRating: 4.7,
        url: 'https://www.doliprane.fr',
      ),
      Product(
        id: '2',
        name: 'Aspégic',
        price: 12.50,
        imageUrl: 'https://tse3.mm.bing.net/th?id=OIP.ujzIGh1GSdCw4HC7oG5gwgHaHa&pid=Api&P=0&h=180',
        description: 'Analgésique et antipyrétique à base d\'aspirine',
        category: 'Analgésiques et Antipyrétiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 85,
        averageRating: 4.5,
        url: 'https://www.aspegic.fr',
      ),
      Product(
        id: '3',
        name: 'Profénid',
        price: 18.75,
        imageUrl: 'https://quefarmacia.com/wp-content/uploads/2020/02/Bi-Profenid.jpg',
        description: 'Analgésique et anti-inflammatoire à base de kétoprofène',
        category: 'Analgésiques et Antipyrétiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 80,
        averageRating: 4.3,
        url: 'https://www.profenid.fr',
      ),
      Product(
        id: '4',
        name: 'Nurofen',
        price: 14.25,
        imageUrl: 'https://tse4.mm.bing.net/th?id=OIP.fPyQ1GjxNgBPrN_VgnIm-gHaHa&pid=Api&P=0&h=180',
        description: 'Analgésique et anti-inflammatoire à base d\'ibuprofène',
        category: 'Analgésiques et Antipyrétiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 90,
        averageRating: 4.6,
        url: 'https://www.nurofen.fr',
      ),
      Product(
        id: '5',
        name: 'Augmentin',
        price: 25.99,
        imageUrl: 'https://tse3.mm.bing.net/th?id=OIP.QwKoCgtOe0Wa5ppzXIhOJQHaFq&pid=Api&P=0&h=180',
        description: 'Antibiotique à base d\'amoxicilline/acide clavulanique',
        category: 'Antibiotiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 80,
        averageRating: 4.6,
        url: 'https://www.augmentin.fr',
      ),
      Product(
        id: '6',
        name: 'Amoxil',
        price: 20.50,
        imageUrl: 'https://tse2.mm.bing.net/th?id=OIP.ZaRAGzdnvPZflqA86x4WFgHaHa&pid=Api&P=0&h=180',
        description: 'Antibiotique à base d\'amoxicilline',
        category: 'Antibiotiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 75,
        averageRating: 4.4,
        url: 'https://www.amoxil.fr',
      ),
      Product(
        id: '7',
        name: 'Flagyl',
        price: 22.75,
        imageUrl: 'https://tse3.mm.bing.net/th?id=OIP.IcrDsgfbdcs-i3XN9tvZUwHaHa&pid=Api&P=0&h=180',
        description: 'Antibiotique à base de métronidazole',
        category: 'Antibiotiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 70,
        averageRating: 4.2,
        url: 'https://www.flagyl.fr',
      ),
      Product(
        id: '8',
        name: 'Zinnat',
        price: 28.99,
        imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.AvU00-neA1GY5yArLld33gHaHa&pid=Api&P=0&h=180',
        description: 'Antibiotique à base de céfuroxime',
        category: 'Antibiotiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 65,
        averageRating: 4.3,
        url: 'https://www.zinnat.fr',
      ),
      Product(
        id: '9',
        name: 'Smecta',
        price: 18.75,
        imageUrl: 'https://tse3.mm.bing.net/th?id=OIP.rFUoqVMOeVyttEwJqSe1NQHaGZ&pid=Api&P=0&h=180',
        description: 'Médicament antidiarrhéique à base de diosmectite',
        category: 'Médicaments Gastro-intestinaux',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 75,
        averageRating: 4.4,
        url: 'https://www.smecta.fr',
      ),
      Product(
        id: '10',
        name: 'Maalox',
        price: 16.50,
        imageUrl: 'https://tse2.mm.bing.net/th?id=OIP.zffX-s_eOtODpVD7HO8l-wHaI7&pid=Api&P=0&h=180',
        description: 'Antiacide à base d\'hydroxyde d\'aluminium/hydroxyde de magnésium',
        category: 'Médicaments Gastro-intestinaux',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'flacon',
        popularity: 80,
        averageRating: 4.5,
        url: 'https://www.maalox.fr',
      ),
      Product(
        id: '11',
        name: 'Motilium',
        price: 19.99,
        imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.PD6rCgF33otzahpyXU1PnAHaHa&pid=Api&P=0&h=180',
        description: 'Antiémétique et agent prokinétique à base de dompéridone',
        category: 'Médicaments Gastro-intestinaux',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 70,
        averageRating: 4.3,
        url: 'https://www.motilium.fr',
      ),
      Product(
        id: '12',
        name: 'Spasfon',
        price: 14.25,
        imageUrl: 'https://tse3.mm.bing.net/th?id=OIP.o_8WaPCXCQAMRso4uJ6ynwHaHa&pid=Api&P=0&h=180',
        description: 'Médicament antispasmodique à base de phloroglucinol',
        category: 'Médicaments Gastro-intestinaux',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 75,
        averageRating: 4.4,
        url: 'https://www.spasfon.fr',
      ),
      Product(
        id: '13',
        name: 'Ventoline',
        price: 22.50,
        imageUrl: 'https://tse2.mm.bing.net/th?id=OIP.CZ_Mm-c_P8jnFeBpv8j5mgHaJw&pid=Api&P=0&h=180',
        description: 'Bronchodilatateur à base de salbutamol',
        category: 'Médicaments Respiratoires',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'inhalateur',
        popularity: 85,
        averageRating: 4.7,
        url: 'https://www.ventoline.fr',
      ),
      Product(
        id: '14',
        name: 'Rhinathiol',
        price: 17.75,
        imageUrl: 'https://tse3.mm.bing.net/th?id=OIP.ybfrDH-LkcIW1qnFybXIRgHaFj&pid=Api&P=0&h=180',
        description: 'Agent mucolytique à base de carbocistéine',
        category: 'Médicaments Respiratoires',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'flacon',
        popularity: 75,
        averageRating: 4.3,
        url: 'https://www.rhinathiol.fr',
      ),
      Product(
        id: '15',
        name: 'Pulmicort',
        price: 29.99,
        imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qWy1jhgmSjRUR7qu6qjUTwHaHa&pid=Api&P=0&h=180',
        description: 'Corticostéroïde inhalé à base de budésonide',
        category: 'Médicaments Respiratoires',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'inhalateur',
        popularity: 80,
        averageRating: 4.5,
        url: 'https://www.pulmicort.fr',
      ),
      Product(
        id: '16',
        name: 'Aerius',
        price: 24.50,
        imageUrl: 'https://tse3.mm.bing.net/th?id=OIP.rGD6LSJB3vZ-khp4hf__nQHaHa&pid=Api&P=0&h=180',
        description: 'Antihistaminique à base de desloratadine',
        category: 'Médicaments Respiratoires',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 70,
        averageRating: 4.4,
        url: 'https://www.aerius.fr',
      ),
      Product(
        id: '17',
        name: 'Tenormine',
        price: 26.75,
        imageUrl: 'https://tse2.mm.bing.net/th?id=OIP.WPtM_6BlkjogP0rZyVRj2AHaEK&pid=Api&P=0&h=180',
        description: 'Bêta-bloquant à base d\'aténolol',
        category: 'Médicaments Cardiovasculaires',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 75,
        averageRating: 4.5,
        url: 'https://www.tenormine.fr',
      ),
      Product(
        id: '19',
        name: 'Aspirine Cardio',
        price: 15.50,
        imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.Z3eTkp5Y3e3zzlQNnEVd1AHaEP&pid=Api&P=0&h=180',
        description: 'Aspirine à faible dose pour la protection cardiovasculaire',
        category: 'Médicaments Cardiovasculaires',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 85,
        averageRating: 4.7,
        url: 'https://www.aspirinecardio.fr',
      ),
      Product(
        id: '20',
        name: 'Sintrom',
        price: 22.25,
        imageUrl: 'https://pharmaco.co.za/wp-content/uploads/2021/08/Sintrom-ANF-3D.png',
        description: 'Anticoagulant à base d\'acénocoumarol',
        category: 'Médicaments Cardiovasculaires',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 70,
        averageRating: 4.4,
        url: 'https://www.sintrom.fr',
      ),

      Product(
        id: '22',
        name: 'Daonil',
        price: 18.75,
        imageUrl: 'https://www.assetpharmacy.com/wp-content/uploads/2017/09/Daonil-Tablets-Glibenclamide-5mg-Tablets-10-Tablets-1.jpg',
        description: 'Médicament antidiabétique à base de glibenclamide',
        category: 'Médicaments Antidiabétiques',
        sellerId: 'pharmacie_locale',
        sellerType: 'pharmacie',
        unit: 'boîte',
        popularity: 75,
        averageRating: 4.4,
        url: 'https://www.daonil.fr',
      ),
    ];
  }
}